/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserDashboardImport } from './routes/user-dashboard'
import { Route as RestorePasswordStep2Import } from './routes/restore-password-step2'
import { Route as RestorePasswordStep1Import } from './routes/restore-password-step1'
import { Route as RegisterFormImport } from './routes/register-form'
import { Route as LoginFormImport } from './routes/login-form'
import { Route as ListingsImport } from './routes/listings'
import { Route as ListingPageImport } from './routes/listing-page'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UserDashboardRoute = UserDashboardImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const RestorePasswordStep2Route = RestorePasswordStep2Import.update({
  id: '/restore-password-step2',
  path: '/restore-password-step2',
  getParentRoute: () => rootRoute,
} as any)

const RestorePasswordStep1Route = RestorePasswordStep1Import.update({
  id: '/restore-password-step1',
  path: '/restore-password-step1',
  getParentRoute: () => rootRoute,
} as any)

const RegisterFormRoute = RegisterFormImport.update({
  id: '/register-form',
  path: '/register-form',
  getParentRoute: () => rootRoute,
} as any)

const LoginFormRoute = LoginFormImport.update({
  id: '/login-form',
  path: '/login-form',
  getParentRoute: () => rootRoute,
} as any)

const ListingsRoute = ListingsImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRoute,
} as any)

const ListingPageRoute = ListingPageImport.update({
  id: '/listing-page',
  path: '/listing-page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/listing-page': {
      id: '/listing-page'
      path: '/listing-page'
      fullPath: '/listing-page'
      preLoaderRoute: typeof ListingPageImport
      parentRoute: typeof rootRoute
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsImport
      parentRoute: typeof rootRoute
    }
    '/login-form': {
      id: '/login-form'
      path: '/login-form'
      fullPath: '/login-form'
      preLoaderRoute: typeof LoginFormImport
      parentRoute: typeof rootRoute
    }
    '/register-form': {
      id: '/register-form'
      path: '/register-form'
      fullPath: '/register-form'
      preLoaderRoute: typeof RegisterFormImport
      parentRoute: typeof rootRoute
    }
    '/restore-password-step1': {
      id: '/restore-password-step1'
      path: '/restore-password-step1'
      fullPath: '/restore-password-step1'
      preLoaderRoute: typeof RestorePasswordStep1Import
      parentRoute: typeof rootRoute
    }
    '/restore-password-step2': {
      id: '/restore-password-step2'
      path: '/restore-password-step2'
      fullPath: '/restore-password-step2'
      preLoaderRoute: typeof RestorePasswordStep2Import
      parentRoute: typeof rootRoute
    }
    '/user-dashboard': {
      id: '/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listing-page': typeof ListingPageRoute
  '/listings': typeof ListingsRoute
  '/login-form': typeof LoginFormRoute
  '/register-form': typeof RegisterFormRoute
  '/restore-password-step1': typeof RestorePasswordStep1Route
  '/restore-password-step2': typeof RestorePasswordStep2Route
  '/user-dashboard': typeof UserDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listing-page': typeof ListingPageRoute
  '/listings': typeof ListingsRoute
  '/login-form': typeof LoginFormRoute
  '/register-form': typeof RegisterFormRoute
  '/restore-password-step1': typeof RestorePasswordStep1Route
  '/restore-password-step2': typeof RestorePasswordStep2Route
  '/user-dashboard': typeof UserDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/listing-page': typeof ListingPageRoute
  '/listings': typeof ListingsRoute
  '/login-form': typeof LoginFormRoute
  '/register-form': typeof RegisterFormRoute
  '/restore-password-step1': typeof RestorePasswordStep1Route
  '/restore-password-step2': typeof RestorePasswordStep2Route
  '/user-dashboard': typeof UserDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/listing-page'
    | '/listings'
    | '/login-form'
    | '/register-form'
    | '/restore-password-step1'
    | '/restore-password-step2'
    | '/user-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/listing-page'
    | '/listings'
    | '/login-form'
    | '/register-form'
    | '/restore-password-step1'
    | '/restore-password-step2'
    | '/user-dashboard'
  id:
    | '__root__'
    | '/'
    | '/listing-page'
    | '/listings'
    | '/login-form'
    | '/register-form'
    | '/restore-password-step1'
    | '/restore-password-step2'
    | '/user-dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListingPageRoute: typeof ListingPageRoute
  ListingsRoute: typeof ListingsRoute
  LoginFormRoute: typeof LoginFormRoute
  RegisterFormRoute: typeof RegisterFormRoute
  RestorePasswordStep1Route: typeof RestorePasswordStep1Route
  RestorePasswordStep2Route: typeof RestorePasswordStep2Route
  UserDashboardRoute: typeof UserDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListingPageRoute: ListingPageRoute,
  ListingsRoute: ListingsRoute,
  LoginFormRoute: LoginFormRoute,
  RegisterFormRoute: RegisterFormRoute,
  RestorePasswordStep1Route: RestorePasswordStep1Route,
  RestorePasswordStep2Route: RestorePasswordStep2Route,
  UserDashboardRoute: UserDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/listing-page",
        "/listings",
        "/login-form",
        "/register-form",
        "/restore-password-step1",
        "/restore-password-step2",
        "/user-dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/listing-page": {
      "filePath": "listing-page.tsx"
    },
    "/listings": {
      "filePath": "listings.tsx"
    },
    "/login-form": {
      "filePath": "login-form.tsx"
    },
    "/register-form": {
      "filePath": "register-form.tsx"
    },
    "/restore-password-step1": {
      "filePath": "restore-password-step1.tsx"
    },
    "/restore-password-step2": {
      "filePath": "restore-password-step2.tsx"
    },
    "/user-dashboard": {
      "filePath": "user-dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
